import { AnimatePresence, motion } from 'framer-motion';
import { ArrowDownRight, ArrowRight, Orbit, Pause, Play, RadioTower } from 'lucide-react';
import { useApp } from '../AppContext';
import { modeOptions, viewOptions } from '../appData';
import { RaceCarScene } from '../RaceCarScene';

export function HeroSection(){
 const{reduced,mode,setMode,view,setView,selected,setSelected,explode,setExplode,autoRotate,setAutoRotate,snapshot,selectedSystem}=useApp();
 return <section id="overview" className="hero"><div className="hero-grid" aria-hidden="true"/><div className="hero-scan" aria-hidden="true"/><div className="session-line"><span>SESSION / RACE SIMULATION 08</span><span>TRACK / HIGH-DOWNFORCE CONFIGURATION</span><span>UTC / +02:00</span></div>
 <div className="hero-copy"><motion.div className="eyebrow" initial={reduced?false:{opacity:0,y:14}} animate={{opacity:1,y:0}} transition={{duration:.6}}><RadioTower size={14}/> PERFORMANCE OPERATING SYSTEM</motion.div><h1><motion.span initial={reduced?false:{y:'105%'}} animate={{y:0}} transition={{duration:.85}}>ENGINEER</motion.span><motion.span initial={reduced?false:{y:'105%'}} animate={{y:0}} transition={{duration:.85,delay:.1}}>THE ADVANTAGE.</motion.span></h1><motion.p initial={reduced?false:{opacity:0,y:16}} animate={{opacity:1,y:0}} transition={{duration:.7,delay:.25}}>A live, interactive performance system where vehicle physics, telemetry, component intelligence and race strategy operate as one decision surface.</motion.p><motion.div className="hero-actions" initial={reduced?false:{opacity:0,y:16}} animate={{opacity:1,y:0}} transition={{duration:.7,delay:.38}}><button className="primary-action" onClick={()=>document.getElementById('twin')?.scrollIntoView({behavior:reduced?'auto':'smooth'})}><span className="live-dot"/> ENTER DIGITAL TWIN <ArrowRight size={16}/></button><button className="text-action" onClick={()=>setMode(mode==='engineering'?'race':'engineering')}><Orbit size={15}/> {mode==='engineering'?'RETURN TO RACE MODE':'OPEN ENGINEERING MODE'}</button></motion.div></div>
 <div className="hero-stage"><RaceCarScene mode={mode} view={view} selected={selected} explode={explode} autoRotate={autoRotate} telemetry={snapshot} onSelect={setSelected}/><div className="car-callout car-callout--front"><span>FRONT LOAD</span><strong>1.84 kN</strong></div><div className="car-callout car-callout--core"><span>PU OUTPUT</span><strong>744 kW</strong></div><div className="car-callout car-callout--rear"><span>AERO BALANCE</span><strong>46.8%</strong></div></div>
 <aside className="control-deck"><div className="control-deck__head"><span>CONTROL DECK / 01</span><strong>MODEL STATE</strong></div><div className="mode-switcher">{modeOptions.map(option=><button key={option.id} className={mode===option.id?'is-active':''} onClick={()=>setMode(option.id)}><span>{option.shortcut}</span><div><strong>{option.label}</strong><small>{option.description}</small></div></button>)}</div><div className="view-switcher"><span>CAMERA PRESET</span><div>{viewOptions.map(option=><button key={option.id} className={view===option.id?'is-active':''} onClick={()=>setView(option.id)} title={`${option.label} view (${option.shortcut})`}>{option.label}</button>)}</div></div><label className="explode-control"><span>EXPLODED ANALYSIS <b>{Math.round(explode*100)}%</b></span><input type="range" min="0" max="1" step="0.02" value={explode} onChange={(event: { target: { value: string } })=>setExplode(Number(event.target.value))}/></label><button className="rotate-toggle" onClick={()=>setAutoRotate((value: boolean)=>!value)}>{autoRotate?<Pause size={14}/>:<Play size={14}/>} {autoRotate?'PAUSE AUTO ORBIT':'RESUME AUTO ORBIT'} <span>SPACE</span></button><div className="keyboard-map"><span>KEYBOARD</span><b>1–3 MODES</b><b>H/F/S/R/T VIEWS</b><b>E EXPLODE</b></div></aside>
 <AnimatePresence mode="wait"><motion.aside className="component-inspector" key={selected} initial={{opacity:0,x:18}} animate={{opacity:1,x:0}} exit={{opacity:0,x:-18}} transition={{duration:.25}}><div className="component-inspector__index">{selectedSystem.index}</div><div><span>{selectedSystem.eyebrow}</span><h2>{selectedSystem.title}</h2><p>{selectedSystem.description}</p></div><div className="component-inspector__metrics"><article><strong>{selectedSystem.primary}</strong><span>{selectedSystem.primaryLabel}</span></article><article><strong>{selectedSystem.secondary}</strong><span>{selectedSystem.secondaryLabel}</span></article></div><div className="component-inspector__status"><i/> {selectedSystem.status}</div></motion.aside></AnimatePresence>
 <div className="hero-telemetry"><article><span>SPEED</span><strong>{snapshot.speed}</strong><small>KM/H</small></article><article><span>GEAR</span><strong>{snapshot.gear}</strong><small>{snapshot.drs?'DRS OPEN':'DRS CLOSED'}</small></article><article><span>ENGINE</span><strong>{snapshot.rpm.toLocaleString()}</strong><small>RPM</small></article><article><span>THROTTLE</span><strong>{snapshot.throttle}</strong><small>%</small></article><article><span>DELTA</span><strong className={snapshot.delta<=0?'is-positive':'is-negative'}>{snapshot.delta>0?'+':''}{snapshot.delta.toFixed(3)}</strong><small>SECONDS</small></article></div><button className="hero-scroll" onClick={()=>document.getElementById('telemetry')?.scrollIntoView({behavior:reduced?'auto':'smooth'})}>LIVE TELEMETRY <ArrowDownRight size={16}/></button></section>;
}
